version: '3'
services:
  app:
    container_name: io_bank_container
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      #- fullstack-postgres          # Uncomment this when using postgres.
      # - fullstack-mysql           # Uncomment this when using mysql.
      - io_bank_db
    networks:
      - io_bank
  #fullstack-postgres:
    #image: postgres:latest
    #container_name: full_db_postgres
    #environment:
      #- POSTGRES_USER=${DB_USER}
      #- POSTGRES_PASSWORD=${DB_PASSWORD}
      #- POSTGRES_DB=${DB_NAME}
      #- DATABASE_HOST=${DB_HOST}
    #ports:
      #- '5432:5432'
    #volumes:
      #- database_postgres:/var/lib/postgresql/data
    #networks:
      #- fullstack

  #pgadmin:
    #image: dpage/pgadmin4
    #container_name: pgadmin_container
    #environment:
      #PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      #PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    #depends_on:
      #- fullstack-postgres
    #ports:
      #- "5050:80"
    #networks:
      #- fullstack
    #restart: unless-stopped


  io_bank_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: io_bank_db_container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - io_bank

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: io_bank_phpmyadmin_container
    depends_on:
      - io_bank_db
    environment:
      - PMA_HOST=${DB_HOST} # Note the "mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - io_bank
volumes:
  api:
  #database_postgres:                  # Uncomment this when using postgres.
  # database_mysql:                   # Uncomment this when using mysql.
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  io_bank:
    driver: bridge
